### ISSUE TITLE
Public transport layout bad display

### ISSUE THREAD

**Issue by nlehuby** [labexp/osmtracker-android-layouts#18] opened 2019-05-02 06:23 UTC
I can't see any labels on the public transport layout.

Here is how it looks like on my phone:
![Screenshot_20190502-080944](https://user-images.githubusercontent.com/919962/57059024-7cc8f000-6cb3-11e9-8a53-ddeb9be4c713.png)

**Comment by adam3497** [comment] 2019-05-21 15:55
Hi @nlehuby 

Thanks for notice this problem. In the past days I was testing your PR #17 and I had the same problem with the size of buttons. With a simple test, changing the size of the label in the first button, I discovered that the problem is related with the old design of the OSMTracker interface. So, this issue will post in the main repository of the app and we'll make a proposal to solve it. 

Thanks again and we'll start working in it as soon as possible.

**Comment by roirobo** [comment] 2019-10-20 06:43
Does it works if you change the size of the icon to 32x32px?

**Comment by roirobo** [comment] 2022-03-05 23:52
I've tried the new version of the app and the buttons display correctly. I suggest to close the issue.

**Closed as completed** 2022-03-12 00:17 UTC
